### ISSUE TITLE
Incompatible with Kvantum/KvYaru

### ISSUE THREAD

**Issue by ryu-ketsueki** [Bonandry/yaru-plus#32] opened 2019-10-24 20:32 UTC
I'm using this icon pack with KvYaru as theme for KDE Plasma. For both Yaru++ and Yaru++-Dark, the icons are not inverted for the toolbars. This is an issue only with Yaru++ Icon Packs, as the other icon packs such as Breeze, Qogir and others, display the icons properly on the toolbars.

This is how it is showing: https://i.postimg.cc/2yFLpF4X/Screenshot-20191024-172604.png
This is how the Yaru++-Dark shows: https://i.postimg.cc/kMxbt9kF/Screenshot-20191024-172627.png
This is how it is supposed to show: https://i.postimg.cc/Wbzscw6F/Screenshot-20191024-173108.png

**Comment by gusbemacbe** [comment] 2019-10-24 23:51
Hello @ryu-ketsueki !

Before, Yaru++ was designed exclusively to light Ubuntu. I, as co-author and the repo's author had an agreement that Yaru++ should be expanded to be supported in many non-Ubuntu and non-GNOME distributions, non-light and mixed themes, but only the folder `apps` is complete. Next month I should focus on it after finishing Adwaita++ and Suru++ 30 jobs. 

If you want it to be solved quickly, as you know how to do it because you showed us how you solved in the third screenshot, you are free to clone our repo, and make a PR.

**Comment by ryu-ketsueki** [comment] 2019-10-27 04:23
> If you want it to be solved quickly, as you know how to do it because you showed us how you solved in the third screenshot, you are free to clone our repo, and make a PR.

Sadly that was a bug with Plasma's icons. I applied Yaru++-Dark after Yaru++ while keeping Dolphin's window open, making only the icons on the toolbar change. Everything changes to the recently applied icon pack if I close and reopen the window. But I will see what I can do. It would appear that some icons are showing grey instead of black. If I learn why they are like that, I may be use it to have them turn all white.

**Comment by gusbemacbe** [comment] 2019-10-27 04:31
Toolbar icons belong to `{actions,status}`. I would change to white colour.
Apps, files and folders icons belongs to `{apps,categories,mimetypes,places/16}`. I would change to black colour or any colour. 

Was it what you were trying to test?

I would create a new alternative icons theme as <code><b>k</b>Yaru++</code>, designed for Plasma/KDE/QT. 

I doubt that the actions and status icons with white colour work in the toolbar, menu bar, bar menu of other apps.

**Comment by gusbemacbe** [comment] 2020-06-28 05:23
Hello @ryu-ketsueki !

I have just added compatibility with Kvantum. It is on the branch `gusbemacbe` and please, use`kYaru++`. Please tell me if it worked with Kvantum.

**Comment by ryu-ketsueki** [comment] 2020-06-29 16:24
> Hello @ryu-ketsueki !
> 
> I have just added compatibility with Kvantum. It is on the branch `gusbemacbe` and please, use`kYaru++`. Please tell me if it worked with Kvantum.

There are many icons missing. I think it may be a problem with inherits. As for the icons already here, few of them are on the right colors. I tested using KvMojaveMixed, which used the mixed light/dark appearance from the original KvYaru. The new one seem to have abandoned it completely. I will see if I can find a similar one and also has the Mixed light/dark appearance as the default Yaru for Ubuntu.

Here is an image of my first test.
![image](https://user-images.githubusercontent.com/39316730/86030879-70e9d280-ba0b-11ea-8157-08971de4a24c.png)

**Comment by gusbemacbe** [comment] 2020-06-29 19:12
Hello @ryu-ketsueki 

I'll investigate this issue.

**Comment by gusbemacbe** [comment] 2020-06-30 20:19
Hi @ryu-ketsueki 

I finally investigated the cause:

![image](https://user-images.githubusercontent.com/2257024/86173061-c13d5f00-baf5-11ea-8b98-b78301ec6050.png)

Because you did not copy `Yaru++` to the icons folder. The `kYaru++` depends on `Yaru++`. 

Still I have to improve some icons because some of them are still white somewhere.

**Comment by gusbemacbe** [comment] 2020-07-01 12:14
@ryu-ketsueki 

I have update the `kYaru++`. Please put both `Yaru++` and `kYaru++` to `~/.local/share/icons`.

**Comment by ryu-ketsueki** [comment] 2020-07-02 20:19
The problem persists. Also, I did extract all folders that the inherits would have asked plus the Dark and Smooth ones as well. I did for the last time I tested as well, so I don't know what may be causing this. The inherits are here no problem.
![image](https://user-images.githubusercontent.com/39316730/86405653-1a3cfc80-bc88-11ea-9b4c-dbf5eaab2bf3.png)

**Comment by gusbemacbe** [comment] 2020-07-02 21:10
Hi @ryu-ketsueki 

1. What's your Linux distro?
2. Did you install Qt5ct?
3. Can you share me small dotfiles (Plasma Look and Feel themes, Latte Dock theme, plugins and icons themes)?

**Comment by gusbemacbe** [comment] 2020-12-07 17:44
Since you do not answer anymore, I must close this issue.

**Closed by gusbemacbe** 2020-12-07 17:44 UTC

**Comment by ryu-ketsueki** [comment] 2020-12-07 21:06
I apologize, I do not have much time to invest on this, even because now KvYaru does not use a dark toolbar anymore, so this would not be necessary anymore. But from what I could tell in the last times I used Yaru++, the kYaru++ is working well.

**Comment by gusbemacbe** [comment] 2020-12-08 21:05
@ryu-ketsueki, I am glad it worked.
